version: 2

jobs:
  build:
    machine: true
    working_directory: /home/circleci/security-news
    steps:
      - checkout

      - run:
          name: Install jq and awscli
          command: |
            sudo apt-get update
            sudo apt-get install -y jq awscli

      - run:
          name: Validate latest json file
          command: |
            chmod +x ./bin/check_json.sh
            ./bin/check_json.sh --json_file=latest.json

      - run:
          name: Push latest json file to s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                echo "push to s3"
                aws s3 cp latest.json s3://security-news-protocol/latest.json
                echo "Setting Cors policy"
                aws s3api put-bucket-cors --bucket security-news-protocol --cors-configuration file://./bin/cors.json
            fi

      - run:
          name: Initialise vote day
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                echo "call api gateway"
                chmod +x ./bin/initialise_vote_of_the_day.sh
                ./bin/initialise_vote_of_the_day.sh
            fi
